dbfilename redis_queue.rdb
dir /Users/user/Documents/resturantOS/frappe-bench/config/pids
pidfile /Users/user/Documents/resturantOS/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/user/Documents/resturantOS/frappe-bench/config/redis_queue.acl
